export { addressRouter } from "./AddressesRouter";
export { hotelFacilityRouter } from "./HotelFacilitiesRouter";
export { hotelRouter } from "./HotelsRouter";
export { photoRouter } from "./PhotosRouter";
export { roomCategoryRouter } from "./RoomCategoriesRouter";
export { roomRouter } from "./RoomsRouter";
export { userRouter } from "./UserRouter";
export { authRouter } from "./AuthRouter";
export { hotelBookingRouter } from "./HotelBookingRouter"
